language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - build-essential
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - build-essential
    - os: osx
      compiler: clang
    - os: windows
    - name: "coverage"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - build-essential
      env:
        - CXXFLAGS="-O0 --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --exclude tests --gcov-options '\-lp' --extension cpp --extension hpp

script:
  - cmake -H. -Bcmake-build-travis
  - cmake --build cmake-build-travis
  - cmake --build cmake-build-travis --target check
